# -*- coding: utf-8 -*-
"""140K.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d70iT8YKXKMl6Y3LcWOgYssD9RnMBb9I
"""

from google.colab import drive
drive.mount('/content/drive')

import os

dataset_path = '/content/drive/MyDrive/140k/test'

# ==============================
# 1. هل المجلد موجود؟
# ==============================
if not os.path.exists(dataset_path):
    print("❌ المجلد غير موجود")
else:
    print("✅ المجلد موجود")

# ==============================
# 2. عرض المحتويات
# ==============================
folders = os.listdir(dataset_path)
print("\n📂 محتويات المجلد:")
for f in folders:
    print("-", f)

# ==============================
# 3. البحث عن الصور
# ==============================
image_extensions = ('.png', '.jpg', '.jpeg', '.tif', '.bmp')

all_images = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(image_extensions):
            all_images.append(os.path.join(root, file))

print("\n🖼 عدد الصور:", len(all_images))

# ==============================
# 4. عرض أول 5 صور
# ==============================
print("\n🔍 أمثلة أسماء الصور:")
for img in all_images[:5]:
    print(img)

# ==============================
# 5. هل فيه Au / Tp؟
# ==============================
if 'real' in folders and 'fake' in folders:
    print("\n✅ القاعدة منظمة (real / fake)")
else:
    print("\n⚠️ القاعدة غير منظمة")

# ==============================
# 6. فحص الأبعاد (عينة)
# ==============================
import cv2

print("\n📏 أبعاد بعض الصور:")

for img_path in all_images[:5]:
    img = cv2.imread(img_path)
    if img is not None:
        print(img_path, "→", img.shape)

import numpy as np
import cv2
import os
import tensorflow as tf
from datetime import datetime

# ==============================
# إنشاء مجلد تجربة جديد
# ==============================
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
exp_name = f"CrossDataset_140K_{timestamp}"

output_base = f'/content/drive/MyDrive/Experiments/{exp_name}'

maps_real_dir = os.path.join(output_base, 'maps', 'real')
maps_fake_dir = os.path.join(output_base, 'maps', 'fake')
masks_dir     = os.path.join(output_base, 'masks')

os.makedirs(maps_real_dir, exist_ok=True)
os.makedirs(maps_fake_dir, exist_ok=True)
os.makedirs(masks_dir, exist_ok=True)

print(f"📂 سيتم الحفظ في: {output_base}")

# ==============================
# تحميل الموديل
# ==============================
model_path = '/content/drive/MyDrive/RgbModels/rgb_autoencoder_model.h5'
model = tf.keras.models.load_model(model_path, compile=False)

# ==============================
# مسارات البيانات (140K)
# ==============================
test_folders = {
    'real': '/content/drive/MyDrive/140k/test/real',
    'fake': '/content/drive/MyDrive/140k/test/fake'
}

# ==========================================
# دالة المعالجة (بدون تغيير فعلي)
# ==========================================
def process_image(img_path, category):
    img_name = os.path.basename(img_path)
    base_name = os.path.splitext(img_name)[0]

    mask_name = f"{category}_{base_name}"

    img = cv2.imread(img_path)
    if img is None:
        return

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (384, 256))
    img_input = np.expand_dims(img_resized / 255.0, axis=0)

    # التنبؤ
    reconstructed = model.predict(img_input, verbose=0)[0]
    original = img_input[0]

    # Residual
    residual = np.mean(np.abs(original - reconstructed), axis=-1)

    # ==========================================
    # حفظ TIFF (maps)
    # ==========================================
    if category == 'real':
        tiff_path = os.path.join(maps_real_dir, f"{base_name}.tiff")
    else:
        tiff_path = os.path.join(maps_fake_dir, f"{base_name}.tiff")

    cv2.imwrite(tiff_path, residual.astype(np.float32))

    # ==========================================
    # إنشاء mask
    # ==========================================
    blurred = cv2.GaussianBlur(residual, (5, 5), 0)

    max_val = np.max(blurred)
    if max_val > 0:
        enhanced = (blurred / max_val * 255).astype(np.uint8)
    else:
        enhanced = np.zeros_like(blurred, dtype=np.uint8)

    thresh_val = np.percentile(enhanced, 95)
    _, binary_mask = cv2.threshold(enhanced, thresh_val, 255, cv2.THRESH_BINARY)

    kernel = np.ones((3, 3), np.uint8)
    binary_mask = cv2.morphologyEx(binary_mask, cv2.MORPH_OPEN, kernel)

    # ==========================================
    # حفظ mask
    # ==========================================
    mask_path = os.path.join(masks_dir, f"{mask_name}.png")
    cv2.imwrite(mask_path, binary_mask)


# ==========================================
# التنفيذ
# ==========================================
for category, folder_path in test_folders.items():
    print(f"\n--- Processing {category} ---")

    images = [f for f in os.listdir(folder_path)
              if f.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp'))]

    for i, name in enumerate(images):
        print(f"[{i+1}/{len(images)}] {name}")
        process_image(os.path.join(folder_path, name), category)

print("\n✅ تم الانتهاء! (140K Cross-Dataset جاهز)")

import os

exp_path = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"  # 👈 عدليه حسب تجربتك

def count_images_in_folder(folder_path):
    image_extensions = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')
    return len([f for f in os.listdir(folder_path)
                if f.lower().endswith(image_extensions)])

folders = {
    "Input_real": "/content/drive/MyDrive/140k/test/real",
    "Input_fake": "/content/drive/MyDrive/140k/test/fake",

    "Maps_real": os.path.join(exp_path, "maps", "real"),
    "Maps_fake": os.path.join(exp_path, "maps", "fake")
}

for name, path in folders.items():
    if not os.path.exists(path):
        print(f"{name}: ❌ path not found")
        continue

    count = count_images_in_folder(path)
    print(f"{name}: {count} images")

import os
import tensorflow as tf
import numpy as np

IMG_SIZE_MAP = 128
IMG_SIZE_RGB = 224
BATCH_SIZE = 64
AUTOTUNE = tf.data.AUTOTUNE

import os

# ==============================
# البحث عن الصور (كما هو بدون تغيير)
# ==============================
def find_rgb_image(rgb_folder, name):
    exts = ['.jpg','.png','.jpeg','.tif','.tiff','.bmp']
    for ext in exts:
        p = os.path.join(rgb_folder, name + ext)
        if os.path.exists(p):
            return p
    return None


def get_all_pairs(map_folder, rgb_folder, label):

    data = []

    for f in os.listdir(map_folder):
        if not f.lower().endswith('.tiff'):
            continue

        name = os.path.splitext(f)[0]

        map_path = os.path.join(map_folder, f)
        rgb_path = find_rgb_image(rgb_folder, name)

        if rgb_path is not None:
            data.append((map_path, rgb_path, label))

    return data


# ==============================
# ✨ المسارات (تم التعديل فقط)
# ==============================

EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

maps_au = os.path.join(EXP_PATH, "maps/real")
maps_tp = os.path.join(EXP_PATH, "maps/fake")

rgb_au = "/content/drive/MyDrive/140k/test/real"
rgb_tp = "/content/drive/MyDrive/140k/test/fake"


# ==============================
# إنشاء البيانات
# ==============================

data_au = get_all_pairs(maps_au, rgb_au, label=0)  # real
data_tp = get_all_pairs(maps_tp, rgb_tp, label=1)  # fake

data = data_au + data_tp

print("Total pairs:", len(data))
print("Sample:", data[:5])

import cv2
import numpy as np
import tensorflow as tf

# ==========================================
# قراءة صور MAP (TIFF)
# ==========================================
def load_map_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
        img = np.zeros((IMG_SIZE_MAP, IMG_SIZE_MAP), dtype=np.uint8)

    if len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

    img = cv2.resize(img, (IMG_SIZE_MAP, IMG_SIZE_MAP))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# قراءة صور RGB (يدعم كل الامتدادات)
# ==========================================
def load_rgb_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path)

    if img is None:
        img = np.zeros((IMG_SIZE_RGB, IMG_SIZE_RGB, 3), dtype=np.uint8)

    img = cv2.resize(img, (IMG_SIZE_RGB, IMG_SIZE_RGB))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# parse_function (النسخة النهائية)
# ==========================================
def parse_function(map_path, rgb_path, label):

    # MAP (TIFF)
    map_img = tf.py_function(load_map_cv2, [map_path], tf.float32)
    map_img.set_shape((IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    # RGB (jpg/png/bmp/tif)
    rgb_img = tf.py_function(load_rgb_cv2, [rgb_path], tf.float32)
    rgb_img.set_shape((IMG_SIZE_RGB, IMG_SIZE_RGB, 3))

    return (map_img, rgb_img), label

# ==========================================
# build_dataset
# ==========================================
def build_dataset(data):

    map_paths = [d[0] for d in data]
    rgb_paths = [d[1] for d in data]
    labels    = [d[2] for d in data]

    dataset = tf.data.Dataset.from_tensor_slices((map_paths, rgb_paths, labels))

    dataset = dataset.map(
        lambda m, r, y: parse_function(m, r, y),
        num_parallel_calls=tf.data.AUTOTUNE
    )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

# СNN للخرائط
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model

def build_map_cnn():

    inp = Input(shape=(IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    x = Conv2D(32,3,activation='relu',padding='same')(inp)
    x = MaxPooling2D()(x)

    x = Conv2D(64,3,activation='relu',padding='same')(x)
    x = MaxPooling2D()(x)

    x = Conv2D(128,3,activation='relu',padding='same')(x)

    x = GlobalAveragePooling2D()(x)

    return Model(inp, x)

#ResNet50 للصور الملونة
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

resnet = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(IMG_SIZE_RGB, IMG_SIZE_RGB, 3)
)

resnet.trainable = False

# Block 7 — استخراج الميزات
map_model = build_map_cnn()

def extract_features(dataset):

    all_features = []
    all_labels = []

    for (maps, rgbs), labels in dataset:

        # CNN features (maps)
        f1 = map_model(maps, training=False)

        # ResNet features (rgb)
        rgbs_resnet = preprocess_input(rgbs * 255.0)
        f2 = resnet(rgbs_resnet, training=False)
        f2 = tf.keras.layers.GlobalAveragePooling2D()(f2)

        # Normalization (سريع)
        f1 = (f1 - tf.reduce_mean(f1)) / (tf.math.reduce_std(f1) + 1e-8)
        f2 = (f2 - tf.reduce_mean(f2)) / (tf.math.reduce_std(f2) + 1e-8)

        # Fusion
        fused = tf.concat([f1, f2], axis=1)

        all_features.append(fused.numpy())
        all_labels.append(labels.numpy())

        print("Processed batch")

    return np.vstack(all_features), np.concatenate(all_labels)

# ==============================
# ✨ المسارات الصحيحة (140K)
# ==============================

EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

MAP_AU = os.path.join(EXP_PATH, "maps/real")
MAP_TP = os.path.join(EXP_PATH, "maps/fake")

RGB_AU = "/content/drive/MyDrive/140k/test/real"
RGB_TP = "/content/drive/MyDrive/140k/test/fake"


# ==============================
# تشغيل النظام (بدون تغيير)
# ==============================

data_au = get_all_pairs(MAP_AU, RGB_AU, 0)
data_tp = get_all_pairs(MAP_TP, RGB_TP, 1)

all_data = data_au + data_tp

print("Total samples:", len(all_data))

dataset = build_dataset(all_data)

features, labels = extract_features(dataset)

print("Feature shape:", features.shape)

# حفظ الميزات
# نفس EXP_PATH المستخدم سابقاً
features_path = os.path.join(EXP_PATH, "features.npy")
labels_path   = os.path.join(EXP_PATH, "labels.npy")

np.save(features_path, features)
np.save(labels_path, labels)

print("✅ Features saved successfully inside experiment folder")

import os
import numpy as np
import matplotlib.pyplot as plt
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve

# ==============================
# المسارات (140K)
# ==============================
EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

features_path = os.path.join(EXP_PATH, "features.npy")
labels_path   = os.path.join(EXP_PATH, "labels.npy")

# ==============================
# تحميل
# ==============================
features = np.load(features_path)
labels   = np.load(labels_path)

# ==============================
# تقسيم
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42, stratify=labels
)

# ==============================
# Scaling
# ==============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ==============================
# تدريب + حساب الوقت
# ==============================
model = LGBMClassifier(n_estimators=300, learning_rate=0.05)

start_train = time.time()
model.fit(X_train, y_train)
end_train = time.time()

train_time = end_train - start_train

# ==============================
# تقييم + حساب الوقت
# ==============================
start_test = time.time()

pred  = model.predict(X_test)
proba = model.predict_proba(X_test)[:,1]

end_test = time.time()

test_time = end_test - start_test

# ==============================
# النتائج
# ==============================
acc = accuracy_score(y_test, pred)
auc = roc_auc_score(y_test, proba)

print("Accuracy:", acc)
print("AUC:", auc)

print("\n⏱ Training Time:", train_time)
print("⏱ Testing Time :", test_time)
print("⏱ Time per sample:", test_time / len(X_test))

# ==============================
# رسم ROC Curve
# ==============================
fpr, tpr, _ = roc_curve(y_test, proba)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {auc:.4f}")
plt.plot([0,1], [0,1], '--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - LightGBM")

plt.legend()
plt.grid()

roc_path = os.path.join(EXP_PATH, "ROC_Curve.png")
plt.savefig(roc_path, dpi=300)

plt.show()

print(f"\n📈 ROC saved in: {roc_path}")

import os
import matplotlib.pyplot as plt
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

# ==============================
# مسار الحفظ (140K)
# ==============================
EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

# ==========================================
# 1. تقرير شامل
# ==========================================
print("\n📊 Classification Report:\n")
print(classification_report(y_test, pred))

# ==========================================
# 2. Confusion Matrix
# ==========================================
cm = confusion_matrix(y_test, pred)

print("\n📌 Confusion Matrix:\n", cm)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.colorbar()

cm_path = os.path.join(EXP_PATH, "Confusion_Matrix.png")
plt.savefig(cm_path, dpi=300)

plt.show()

# ==========================================
# 3. ROC Curve + AUC
# ==========================================
fpr, tpr, thresholds = roc_curve(y_test, proba)
roc_auc = auc(fpr, tpr)

print("\n📈 AUC:", roc_auc)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

roc_path = os.path.join(EXP_PATH, "ROC_Curve_Final.png")
plt.savefig(roc_path, dpi=300)

plt.show()

# ==========================================
# 4. Time Report
# ==========================================
print("\n⏱ Training Time:", train_time)
print("⏱ Testing Time :", test_time)
print("⏱ Time per sample:", test_time / len(y_test))

print("\n📂 Saved files:")
print("Confusion Matrix →", cm_path)
print("ROC Curve       →", roc_path)

# تفسير الفيجرات
import shap

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

import os
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score

# ==============================
# المسارات (140K)
# ==============================
EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

features_path = os.path.join(EXP_PATH, "features.npy")
labels_path   = os.path.join(EXP_PATH, "labels.npy")

# ==============================
# تحميل
# ==============================
features = np.load(features_path)
labels   = np.load(labels_path)

# ==============================
# تقسيم
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42, stratify=labels
)

# ==============================
# Scaling
# ==============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ==============================
# النماذج
# ==============================
models = {
    "RandomForest": RandomForestClassifier(n_estimators=200),
    "SVM": SVC(probability=True),
    "XGBoost": XGBClassifier(eval_metric='logloss')
}

# ==============================
# التدريب والتقييم + الوقت
# ==============================
for name, m in models.items():

    start_train = time.time()
    m.fit(X_train, y_train)
    end_train = time.time()

    train_time = end_train - start_train

    start_test = time.time()

    pred  = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]

    end_test = time.time()

    test_time = end_test - start_test

    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, pred))
    print("AUC:", roc_auc_score(y_test, proba))

    print("⏱ Training Time:", train_time)
    print("⏱ Testing Time :", test_time)
    print("⏱ Time per sample:", test_time / len(X_test))

!pip install catboost

from sklearn.ensemble import ExtraTreesClassifier
from catboost import CatBoostClassifier

import os
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score

# ==============================
# المسارات (140K)
# ==============================
EXP_PATH = "/content/drive/MyDrive/Experiments/CrossDataset_140K_20260419_180158"

features_path = os.path.join(EXP_PATH, "features.npy")
labels_path   = os.path.join(EXP_PATH, "labels.npy")

# ==============================
# تحميل
# ==============================
features = np.load(features_path)
labels   = np.load(labels_path)

# ==============================
# تقسيم
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42, stratify=labels
)

# ==============================
# Scaling
# ==============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ==============================
# النماذج
# ==============================
models = {
    "ExtraTrees": ExtraTreesClassifier(n_estimators=200),
    "CatBoost": CatBoostClassifier(verbose=0)
}

# ==============================
# التدريب والتقييم + الوقت
# ==============================
for name, m in models.items():

    start_train = time.time()
    m.fit(X_train, y_train)
    end_train = time.time()

    train_time = end_train - start_train

    start_test = time.time()

    pred  = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]

    end_test = time.time()

    test_time = end_test - start_test

    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, pred))
    print("AUC:", roc_auc_score(y_test, proba))

    print("⏱ Training Time:", train_time)
    print("⏱ Testing Time :", test_time)
    print("⏱ Time per sample:", test_time / len(X_test))

from sklearn.ensemble import StackingClassifier, RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import time

# ✔ استخدمي CatBoost فقط إذا مثبت
try:
    from catboost import CatBoostClassifier
    use_cat = True
except:
    use_cat = False

# ==============================
# Base Models
# ==============================
estimators = [
    ('lgbm', LGBMClassifier(n_estimators=200)),
    ('rf', RandomForestClassifier(n_estimators=200)),
    ('xgb', XGBClassifier(eval_metric='logloss')),
    ('extra', ExtraTreesClassifier(n_estimators=200))
]

if use_cat:
    estimators.append(('cat', CatBoostClassifier(verbose=0)))

# ==============================
# Stacking Model
# ==============================
stack_model = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(max_iter=1000),  # 🔥 مهم
    cv=5,                                               # 🔥 مهم
    n_jobs=-1                                           # 🔥 تسريع
)

# ==============================
# Training
# ==============================
start_train = time.time()
stack_model.fit(X_train, y_train)
end_train = time.time()

train_time = end_train - start_train

# ==============================
# Testing
# ==============================
start_test = time.time()

pred  = stack_model.predict(X_test)
proba = stack_model.predict_proba(X_test)[:,1]

end_test = time.time()

test_time = end_test - start_test

# ==============================
# النتائج
# ==============================
print("\n🔹 Stacking Model (Enhanced)")
print("Accuracy:", accuracy_score(y_test, pred))
print("AUC:", roc_auc_score(y_test, proba))

print("⏱ Training Time:", train_time)
print("⏱ Testing Time :", test_time)
print("⏱ Time per sample:", test_time / len(X_test))

from sklearn.ensemble import VotingClassifier, RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import time

# ✔ CatBoost اختياري
try:
    from catboost import CatBoostClassifier
    use_cat = True
except:
    use_cat = False

# ==============================
# Base Models
# ==============================
estimators = [
    ('lgbm', LGBMClassifier(n_estimators=200, random_state=42, n_jobs=-1)),
    ('rf', RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)),
    ('xgb', XGBClassifier(eval_metric='logloss', random_state=42, n_jobs=-1)),
    ('extra', ExtraTreesClassifier(n_estimators=200, random_state=42, n_jobs=-1))
]

if use_cat:
    estimators.append(('cat', CatBoostClassifier(verbose=0)))

# ==============================
# Voting Model
# ==============================
voting_model = VotingClassifier(
    estimators=estimators,
    voting='soft',   # ✔ مهم
    n_jobs=-1        # ✔ تسريع
)

# ==============================
# Training
# ==============================
start_train = time.time()
voting_model.fit(X_train, y_train)
end_train = time.time()

train_time = end_train - start_train

# ==============================
# Testing
# ==============================
start_test = time.time()

pred  = voting_model.predict(X_test)
proba = voting_model.predict_proba(X_test)[:,1]

end_test = time.time()

test_time = end_test - start_test

# ==============================
# النتائج
# ==============================
print("\n🔹 Soft Voting Ensemble (Enhanced)")
print("Accuracy:", accuracy_score(y_test, pred))
print("AUC:", roc_auc_score(y_test, proba))

print("⏱ Training Time:", train_time)
print("⏱ Testing Time :", test_time)
print("⏱ Time per sample:", test_time / len(X_test))

import time
import pandas as pd

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, StackingClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# ==============================
# تعريف النماذج
# ==============================
models = {
    "LightGBM": LGBMClassifier(n_estimators=300),
    "RandomForest": RandomForestClassifier(n_estimators=200),
    "ExtraTrees": ExtraTreesClassifier(n_estimators=200),
    "XGBoost": XGBClassifier(eval_metric='logloss'),
    "CatBoost": CatBoostClassifier(verbose=0),
    "SVM": SVC(probability=True)
}

# ==============================
# Stacking
# ==============================
stack_model = StackingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(n_estimators=200)),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    final_estimator=LogisticRegression()
)

# ==============================
# Voting
# ==============================
voting_model = VotingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(n_estimators=200)),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    voting='soft'
)

# ==============================
# إضافة للـ dictionary
# ==============================
models["Stacking"] = stack_model
models["Voting"] = voting_model

# ==============================
# تشغيل كل النماذج
# ==============================
results = []

for name, m in models.items():

    # ⏱ Training Time
    start_train = time.time()
    m.fit(X_train, y_train)
    end_train = time.time()
    train_time = end_train - start_train

    # ⏱ Testing Time
    start_test = time.time()
    pred  = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]
    end_test = time.time()
    test_time = end_test - start_test

    # حفظ النتائج
    results.append([
        name,
        accuracy_score(y_test, pred),
        roc_auc_score(y_test, proba),
        train_time,
        test_time,
        test_time / len(X_test)
    ])

# ==============================
# إنشاء الجدول
# ==============================
df = pd.DataFrame(results, columns=[
    "Model",
    "Accuracy",
    "AUC",
    "Training Time (s)",
    "Testing Time (s)",
    "Time per Sample (s)"
])

print(df)

# ==============================
# حفظ النتائج داخل مجلد التجربة
# ==============================
results_path = os.path.join(EXP_PATH, "results.csv")

df.to_csv(results_path, index=False)

print("\n📂 Results saved in:", results_path)

excel_path = os.path.join(EXP_PATH, "results.xlsx")
df.to_excel(excel_path, index=False)

print("📊 Excel saved in:", excel_path)