# -*- coding: utf-8 -*-
"""AutoEncoderWithRGBcolor CASIAv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_fv5sHt9SDoBOCTgb1CO02c6RUSUnrk
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import cv2
import os
import tensorflow as tf
from google.colab import drive
from tensorflow.keras import layers, models, optimizers, callbacks


dataset_path = '/content/drive/MyDrive/CASIA2/Au' # تأكدي أن هذا المجلد يحتوي على الصور الملونة
save_model_path = '/content/drive/MyDrive/RgbModels/rgb_autoencoder_model.h5'
IMG_H, IMG_W = 256, 384

# ==========================================
# 1. دالة تحميل الصور الملونة (RGB)
# ==========================================
def load_rgb_data(path, limit=2000):
    images = []
    if not os.path.exists(path):
        print(f"Error: Path {path} not found!")
        return np.array([])

    filenames = os.listdir(path)[:limit]
    print(f"Loading {len(filenames)} images...")

    for name in filenames:
        img = cv2.imread(os.path.join(path, name))
        if img is not None:
            # تحويل من BGR (الافتراضي في OpenCV) إلى RGB
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_W, IMG_H))
            images.append(img / 255.0) # التطبيع (Normalization)

    return np.array(images)

X_train = load_rgb_data(dataset_path)

# ==========================================
# 3. بناء هيكل الـ Autoencoder للصور الملونة
# ==========================================
def build_rgb_autoencoder(input_shape=(256, 384, 3)):
    inputs = layers.Input(shape=input_shape)

    # --- Encoder ---
    # طبقة Conv الأولى لاستخراج الميزات اللونية
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
    x = layers.MaxPooling2D((2, 2), padding='same')(x)

    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = layers.MaxPooling2D((2, 2), padding='same')(x)

    # --- Bottleneck ---
    # نستخدم Dropout مرتفع لمنع الموديل من "حفظ" الصور (Overfitting)
    # هذا يضمن أنه سيفشل في إعادة بناء المناطق الغريبة (المزورة) لاحقاً
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = layers.Dropout(0.5)(x)

    # --- Decoder ---
    x = layers.UpSampling2D((2, 2))(x)
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)

    x = layers.UpSampling2D((2, 2))(x)
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)

    # المخرج: 3 قنوات ملونة مع Sigmoid لضمان قيم بين 0 و 1
    outputs = layers.Conv2D(3, (3, 3), activation='sigmoid', padding='same')(x)

    return models.Model(inputs, outputs)

# ==========================================
# 4. إعدادات التدريب والتشغيل
# ==========================================
if X_train.size > 0:
    model = build_rgb_autoencoder()

    # نستخدم Adam optimizer مع Mean Absolute Error (MAE)
    # الـ MAE أفضل هنا لإظهار الفروقات الحادة في التزوير
    model.compile(optimizer=optimizers.Adam(learning_rate=1e-4), loss='mae')

    # الحفاظ على أفضل نسخة من الموديل
    checkpoint = callbacks.ModelCheckpoint(save_model_path, save_best_only=True, monitor='loss')

    print("Starting Training")
    model.fit(
        X_train, X_train, # الموديل يتعلم إعادة بناء نفس الصورة
        epochs=100,
        batch_size=16,
        shuffle=True,
        callbacks=[checkpoint]
    )

    print(f"Training finished! Model saved at: {save_model_path}")
else:
    print("No data loaded. Check your path.")

#  لتوليد الخرائط ... كود مطور
import numpy as np
import cv2
import os
import tensorflow as tf

# تحميل الموديل
model_path = '/content/drive/MyDrive/RgbModels/rgb_autoencoder_model.h5'
model = tf.keras.models.load_model(model_path, compile=False)

# مسارات البيانات
test_folders = {
    'Au': '/content/drive/MyDrive/resized_images/Au',
    'Tp': '/content/drive/MyDrive/resized_images/Tp'
}

# مجلد الإخراج
output_base = '/content/drive/MyDrive/Final_Maps_Organized'

maps_au_dir = os.path.join(output_base, 'maps', 'Au')
maps_tp_dir = os.path.join(output_base, 'maps', 'Tp')
masks_dir   = os.path.join(output_base, 'masks')

os.makedirs(maps_au_dir, exist_ok=True)
os.makedirs(maps_tp_dir, exist_ok=True)
os.makedirs(masks_dir, exist_ok=True)

# ==========================================
# دالة المعالجة
# ==========================================
def process_image(img_path, category):
    img_name = os.path.basename(img_path)
    base_name = os.path.splitext(img_name)[0]

    # اسم جديد للماسك فقط
    mask_name = f"{category}_{base_name}"

    # قراءة الصورة
    img = cv2.imread(img_path)
    if img is None:
        return

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, (384, 256))
    img_input = np.expand_dims(img_resized / 255.0, axis=0)

    # التنبؤ
    reconstructed = model.predict(img_input, verbose=0)[0]
    original = img_input[0]

    # Residual
    residual = np.mean(np.abs(original - reconstructed), axis=-1)

    # ==========================================
    # حفظ TIFF (maps)
    # ==========================================
    if category == 'Au':
        tiff_path = os.path.join(maps_au_dir, f"{base_name}.tiff")
    else:
        tiff_path = os.path.join(maps_tp_dir, f"{base_name}.tiff")

    cv2.imwrite(tiff_path, residual.astype(np.float32))

    # ==========================================
    # إنشاء mask
    # ==========================================
    blurred = cv2.GaussianBlur(residual, (5, 5), 0)

    max_val = np.max(blurred)
    if max_val > 0:
        enhanced = (blurred / max_val * 255).astype(np.uint8)
    else:
        enhanced = np.zeros_like(blurred, dtype=np.uint8)

    # Threshold تكيفي
    thresh_val = np.percentile(enhanced, 97)
    _, binary_mask = cv2.threshold(enhanced, thresh_val, 255, cv2.THRESH_BINARY)

    # تنظيف
    kernel = np.ones((3, 3), np.uint8)
    binary_mask = cv2.morphologyEx(binary_mask, cv2.MORPH_OPEN, kernel)

    # ==========================================
    # حفظ mask (في مجلد واحد)
    # ==========================================
    mask_path = os.path.join(masks_dir, f"{mask_name}.png")
    cv2.imwrite(mask_path, binary_mask)


# ==========================================
# تنفيذ على كل الصور
# ==========================================
for category, folder_path in test_folders.items():
    print(f"\n--- Processing {category} ---")

    images = [f for f in os.listdir(folder_path)
          if f.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp'))]

    for i, name in enumerate(images):
        print(f"[{i+1}/{len(images)}] {name}")
        process_image(os.path.join(folder_path, name), category)

print("\n✅ تم الانتهاء! التنظيم مطابق لطلبك 100%")

# لمعرفة عدد الصور الناتجة
import os

def count_images_in_folder(folder_path):
    image_extensions = ('.png', '.jpg', '.jpeg', '.tif', '.tiff')

    images = [f for f in os.listdir(folder_path)
              if f.lower().endswith(image_extensions)]

    return len(images)

# المسارات
folders = {
    "Au": "/content/drive/MyDrive/resized_images/Tp",
    "Tp": "/content/drive/MyDrive/Final_Maps_Organized/maps/Tp"
}

# الحساب
for name, path in folders.items():
    count = count_images_in_folder(path)
    print(f"{name}: {count} images")