# -*- coding: utf-8 -*-
"""ClassifficationwithFussion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9ZmqCQNlLUdrQT2Ti7qv65H1WjzwuHt
"""

!pip install tensorflow_hub

from google.colab import drive
drive.mount('/content/drive')

import os
import tensorflow as tf
import numpy as np

IMG_SIZE_MAP = 128
IMG_SIZE_RGB = 224
BATCH_SIZE = 64
AUTOTUNE = tf.data.AUTOTUNE

#البحث عن الصور
def find_rgb_image(rgb_folder, name):
    exts = ['.jpg','.png','.jpeg','.tif','.tiff','.bmp']
    for ext in exts:
        p = os.path.join(rgb_folder, name + ext)
        if os.path.exists(p):
            return p
    return None


def get_all_pairs(map_folder, rgb_folder, label):

    data = []

    for f in os.listdir(map_folder):
        if not f.lower().endswith('.tiff'):
            continue

        name = os.path.splitext(f)[0]

        map_path = os.path.join(map_folder, f)
        rgb_path = find_rgb_image(rgb_folder, name)

        if rgb_path is not None:
            data.append((map_path, rgb_path, label))

    return data

import cv2
import numpy as np
import tensorflow as tf

# ==========================================
# قراءة صور MAP (TIFF)
# ==========================================
def load_map_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
        img = np.zeros((IMG_SIZE_MAP, IMG_SIZE_MAP), dtype=np.uint8)

    if len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

    img = cv2.resize(img, (IMG_SIZE_MAP, IMG_SIZE_MAP))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# قراءة صور RGB (يدعم كل الامتدادات)
# ==========================================
def load_rgb_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path)

    if img is None:
        img = np.zeros((IMG_SIZE_RGB, IMG_SIZE_RGB, 3), dtype=np.uint8)

    img = cv2.resize(img, (IMG_SIZE_RGB, IMG_SIZE_RGB))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# parse_function (النسخة النهائية)
# ==========================================
def parse_function(map_path, rgb_path, label):

    # MAP (TIFF)
    map_img = tf.py_function(load_map_cv2, [map_path], tf.float32)
    map_img.set_shape((IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    # RGB (jpg/png/bmp/tif)
    rgb_img = tf.py_function(load_rgb_cv2, [rgb_path], tf.float32)
    rgb_img.set_shape((IMG_SIZE_RGB, IMG_SIZE_RGB, 3))

    return (map_img, rgb_img), label

# ==========================================
# build_dataset
# ==========================================
def build_dataset(data):

    map_paths = [d[0] for d in data]
    rgb_paths = [d[1] for d in data]
    labels    = [d[2] for d in data]

    dataset = tf.data.Dataset.from_tensor_slices((map_paths, rgb_paths, labels))

    dataset = dataset.map(
        lambda m, r, y: parse_function(m, r, y),
        num_parallel_calls=tf.data.AUTOTUNE
    )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

# СNN للخرائط
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model

def build_map_cnn():

    inp = Input(shape=(IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    x = Conv2D(32,3,activation='relu',padding='same')(inp)
    x = MaxPooling2D()(x)

    x = Conv2D(64,3,activation='relu',padding='same')(x)
    x = MaxPooling2D()(x)

    x = Conv2D(128,3,activation='relu',padding='same')(x)

    x = GlobalAveragePooling2D()(x)

    return Model(inp, x)

#ResNet50 للصور الملونة
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

resnet = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(IMG_SIZE_RGB, IMG_SIZE_RGB, 3)
)

resnet.trainable = False

# Block 7 — استخراج الميزات
map_model = build_map_cnn()

def extract_features(dataset):

    all_features = []
    all_labels = []

    for (maps, rgbs), labels in dataset:

        # CNN features (maps)
        f1 = map_model(maps, training=False)

        # ResNet features (rgb)
        rgbs_resnet = preprocess_input(rgbs * 255.0)
        f2 = resnet(rgbs_resnet, training=False)
        f2 = tf.keras.layers.GlobalAveragePooling2D()(f2)

        # Normalization (سريع)
        f1 = (f1 - tf.reduce_mean(f1)) / (tf.math.reduce_std(f1) + 1e-8)
        f2 = (f2 - tf.reduce_mean(f2)) / (tf.math.reduce_std(f2) + 1e-8)

        # Fusion
        fused = tf.concat([f1, f2], axis=1)

        all_features.append(fused.numpy())
        all_labels.append(labels.numpy())

        print("Processed batch")

    return np.vstack(all_features), np.concatenate(all_labels)

# تشغيل النظام
MAP_AU = "/content/drive/MyDrive/Final_Maps_Organized/maps/Au"
MAP_TP = "/content/drive/MyDrive/Final_Maps_Organized/maps/Tp"

RGB_AU = "/content/drive/MyDrive/resized_images/Au"
RGB_TP = "/content/drive/MyDrive/resized_images/Tp"

data_au = get_all_pairs(MAP_AU, RGB_AU, 0)
data_tp = get_all_pairs(MAP_TP, RGB_TP, 1)

all_data = data_au + data_tp

print("Total samples:", len(all_data))

dataset = build_dataset(all_data)

features, labels = extract_features(dataset)

print("Feature shape:", features.shape)

# حفظ الميزات
# حفظ في Google Drive
np.save("/content/drive/MyDrive/CASIAfeatures.npy", features)
np.save("/content/drive/MyDrive/CASIAlabels.npy", labels)

print("✅ Features saved successfully")

# التدريب
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score
import time

# تحميل
features = np.load("/content/drive/MyDrive/CASIAfeatures.npy")
labels   = np.load("/content/drive/MyDrive/CASIAlabels.npy")

# تقسيم
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# تدريب
start_train = time.time()

model = LGBMClassifier(n_estimators=300, learning_rate=0.05)
model.fit(X_train, y_train)

train_time = time.time() - start_train

# تقييم
start_test = time.time()

pred = model.predict(X_test)
proba = model.predict_proba(X_test)[:,1]

precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
test_time = time.time() - start_test

print("Accuracy:", accuracy_score(y_test, pred))
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", roc_auc_score(y_test, proba))

print("Training Time (s):", train_time)
print("Testing Time (s):", test_time)
print("Time per Sample (s):", test_time / len(X_test))

# تقرير بالنتائج النهائية والرسومات التوضيحية
import matplotlib.pyplot as plt
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

# ==========================================
# 1. تقرير شامل
# ==========================================
print("\n📊 Classification Report:\n")
print(classification_report(y_test, pred))

# ==========================================
# 2. Confusion Matrix
# ==========================================
cm = confusion_matrix(y_test, pred)

print("\n📌 Confusion Matrix:\n", cm)

# رسمها
plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.colorbar()
plt.show()

# ==========================================
# 3. ROC Curve + AUC
# ==========================================
fpr, tpr, thresholds = roc_curve(y_test, proba)
roc_auc = auc(fpr, tpr)

print("\n📈 AUC:", roc_auc)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')  # خط عشوائي
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# تفسير الفيجرات
import shap

explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

# تجربة خوارزميات اخرى Random Forest + SVM + XGBoost
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
import os
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from sklearn.ensemble import ExtraTreesClassifier
from catboost import CatBoostClassifier
import time
import pandas as pd

# تحميل
features = np.load("/content/drive/MyDrive/CASIAfeatures.npy")
labels   = np.load("/content/drive/MyDrive/CASIAlabels.npy")

# تقسيم
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "LightGBM": LGBMClassifier(n_estimators=300),

    "RandomForest": RandomForestClassifier(
        n_estimators=200
    ),

    "ExtraTrees": ExtraTreesClassifier(
        n_estimators=500,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        eval_metric='logloss'
    ),

    "CatBoost": CatBoostClassifier(
        verbose=0
    ),

    "SVM": SVC(
        probability=True
    )
}

results = []

for name, m in models.items():

    # Training Time
    start_train = time.time()

    m.fit(X_train, y_train)

    train_time = time.time() - start_train

    # Testing Time
    start_test = time.time()

    pred = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]

    test_time = time.time() - start_test

    acc = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    auc = roc_auc_score(y_test, proba)
    f1 = f1_score(y_test, pred)

    results.append([
        name,
        acc,
        precision,
        recall,
        f1,
        auc,
        train_time,
        test_time,
        test_time / len(X_test)
    ])

    print(f"\n{name}")
    print("Accuracy:", acc)
    print("precision:", precision)
    print("recall:", recall)
    print("F1-Score:", f1)
    print("AUC:", auc)
    print("Training Time:", train_time)
    print("Testing Time:", test_time)

    df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "AUC",
        "Training Time (s)",
        "Testing Time (s)",
        "Time per Sample (s)"
    ]
)

!pip install catboost -q

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import time

stack_model = StackingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(n_estimators=200)),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    final_estimator=LogisticRegression(),
    n_jobs=-1
)

# Training Time
start_train = time.time()

stack_model.fit(X_train, y_train)

train_time = time.time() - start_train

# Testing Time
start_test = time.time()

pred = stack_model.predict(X_test)
proba = stack_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# Metrics
acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc = roc_auc_score(y_test, proba)

print("\n🔹 Stacking Ensemble")

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", test_time / len(X_test))

from sklearn.ensemble import VotingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import time

voting_model = VotingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(n_estimators=200)),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    voting='soft'
)

# Training Time
start_train = time.time()

voting_model.fit(X_train, y_train)

train_time = time.time() - start_train

# Testing Time
start_test = time.time()

pred = voting_model.predict(X_test)
proba = voting_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# Metrics
acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc = roc_auc_score(y_test, proba)

print("\n🔹 Soft Voting Ensemble")

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", test_time / len(X_test))

results = []

models = {
    "LightGBM": LGBMClassifier(n_estimators=300),
    "RandomForest": RandomForestClassifier(n_estimators=200),
    "XGBoost": XGBClassifier(eval_metric='logloss')
}

for name, m in models.items():
    m.fit(X_train, y_train)
    pred = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]

    results.append([name,
                    accuracy_score(y_test, pred),
                    roc_auc_score(y_test, proba)])

import pandas as pd
df = pd.DataFrame(results, columns=["Model", "Accuracy", "AUC"])
print(df)

import pandas as pd

data = [
    ["LightGBM", 0.9921, 0.9874, 0.9932, 0.9903, 0.9994, 29.56, 0.0517],
    ["RandomForest", 0.8344, 0.8167, 0.7641, 0.7895, 0.9143, 135.24, 0.2555],
    ["ExtraTrees", 0.7401, 0.7176, 0.5945, 0.6503, 0.8378, 57.35, 0.8454],
    ["XGBoost", 0.9330, 0.9085, 0.9288, 0.9186, 0.9817, 23.29, 0.0100],
    ["CatBoost", 0.9489, 0.9350, 0.9396, 0.9373, 0.9890, 111.99, 0.0623],
    ["SVM", 0.7805, 0.7077, 0.7836, 0.7438, 0.8604, 756.84, 96.8503]
]

df = pd.DataFrame(
    data,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "AUC",
        "Training Time (s)",
        "Testing Time (s)"
    ]
)

print(df)

# ==========================================
# CASIA Final Results Table
# ==========================================

import pandas as pd
import os

# حددي أي مجلد تريدين الحفظ فيه
output_base = "/content/drive/MyDrive/Experiments/CASIA_Final"

os.makedirs(output_base, exist_ok=True)

# ==========================================
# النتائج النهائية
# ==========================================

results = [

    {
        "Model": "LightGBM",
        "Accuracy": 99.2076,
        "Precision": 98.7403,
        "Recall": 99.3177,
        "F1-Score": 99.0282,
        "AUC": 99.9410,
        "Training Time (s)": 27.6585,
        "Testing Time (s)": 0.0494,
        "Time per Sample (s)": 0.04935479164123535 / 2524
    },

    {
        "Model": "Stacking Ensemble",
        "Accuracy": 98.9303,
        "Precision": 98.5423,
        "Recall": 98.8304,
        "F1-Score": 98.6861,
        "AUC": 99.9019,
        "Training Time (s)": 907.8108,
        "Testing Time (s)": 0.7691,
        "Time per Sample (s)": 0.0003047
    },

    {
        "Model": "Soft Voting Ensemble",
        "Accuracy": 96.1965,
        "Precision": 94.2015,
        "Recall": 96.5887,
        "F1-Score": 95.3802,
        "AUC": 99.2005,
        "Training Time (s)": 308.6060,
        "Testing Time (s)": 0.7418,
        "Time per Sample (s)": 0.0002939
    },

    {
        "Model": "CatBoost",
        "Accuracy": 94.8891,
        "Precision": 93.5015,
        "Recall": 93.9571,
        "F1-Score": 93.7287,
        "AUC": 98.9005,
        "Training Time (s)": 110.7253,
        "Testing Time (s)": 0.0593,
        "Time per Sample (s)": 0.05930757522583008 / 2524
    },

    {
        "Model": "XGBoost",
        "Accuracy": 93.3043,
        "Precision": 90.8484,
        "Recall": 92.8849,
        "F1-Score": 91.8554,
        "AUC": 98.1670,
        "Training Time (s)": 23.4534,
        "Testing Time (s)": 0.0102,
        "Time per Sample (s)": 0.01022648811340332 / 2524
    },

    {
        "Model": "Random Forest",
        "Accuracy": 83.5182,
        "Precision": 82.1730,
        "Recall": 75.9259,
        "F1-Score": 78.9260,
        "AUC": 91.6841,
        "Training Time (s)": 135.5021,
        "Testing Time (s)": 0.2798,
        "Time per Sample (s)": 0.2798497676849365 / 2524
    },

    {
        "Model": "SVM",
        "Accuracy": 78.0507,
        "Precision": 70.7746,
        "Recall": 78.3626,
        "F1-Score": 74.3756,
        "AUC": 86.0402,
        "Training Time (s)": 757.3367,
        "Testing Time (s)": 97.7809,
        "Time per Sample (s)": 97.78088235855103 / 2524
    },

    {
        "Model": "Extra Trees",
        "Accuracy": 74.0095,
        "Precision": 71.7647,
        "Recall": 59.4542,
        "F1-Score": 65.0320,
        "AUC": 83.7791,
        "Training Time (s)": 57.3538,
        "Testing Time (s)": 0.8454,
        "Time per Sample (s)": 0.8454205989837646 / 2524
    }
]

# ==========================================
# إنشاء الجدول
# ==========================================

df = pd.DataFrame(results)

df = df.sort_values(
    by="Accuracy",
    ascending=False
)

print(df)

# ==========================================
# حفظ
# ==========================================

excel_path = os.path.join(
    output_base,
    "CASIA_Final_Results.xlsx"
)

csv_path = os.path.join(
    output_base,
    "CASIA_Final_Results.csv"
)

df.to_excel(excel_path, index=False)
df.to_csv(csv_path, index=False)

print("\n✅ CASIA Final Results Saved")
print("📄 Excel:", excel_path)
print("📄 CSV  :", csv_path)