# -*- coding: utf-8 -*-
"""CoMoFoDclassefier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMih5Vm86yOuWq9CNsNXQTm1ZME7SJ3W
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install catboost -q

# ==========================================
# Train LightGBM + XGBoost + CatBoost
# CoMoFoD Dataset
# ==========================================

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import numpy as np
import pandas as pd
import time
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# ==========================================
# Paths
# ==========================================

OLD_EXP_PATH = "/content/drive/MyDrive/Experiments/CoMoFoD_Test_20260418_175430"

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

os.makedirs(output_base, exist_ok=True)

# ==========================================
# Load Features
# ==========================================

features = np.load(
    os.path.join(OLD_EXP_PATH, "features.npy")
)

labels = np.load(
    os.path.join(OLD_EXP_PATH, "labels.npy")
)

print("Features shape:", features.shape)
print("Labels shape:", labels.shape)

# ==========================================
# Train/Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    features,
    labels,
    test_size=0.20,
    random_state=42,
    stratify=labels
)

# ==========================================
# Feature Scaling
# ==========================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ==========================================
# Models
# ==========================================

models = {

    "LightGBM": LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        eval_metric='logloss',
        random_state=42
    ),

    "CatBoost": CatBoostClassifier(
        verbose=0,
        random_state=42
    )
}

# ==========================================
# Train Models
# ==========================================

trained_models = {}

results = []

for name, model in models.items():

    print(f"\n{'='*50}")
    print(f"Training {name}")
    print(f"{'='*50}")

    start_train = time.time()

    model.fit(X_train, y_train)

    train_time = time.time() - start_train

    trained_models[name] = model

    start_test = time.time()

    pred = model.predict(X_test)
    proba = model.predict_proba(X_test)[:,1]

    test_time = time.time() - start_test

    acc = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc_score = roc_auc_score(y_test, proba)

    results.append([
        name,
        acc,
        precision,
        recall,
        f1,
        auc_score,
        train_time,
        test_time,
        test_time / len(X_test)
    ])

    print("Accuracy :", acc)
    print("Precision:", precision)
    print("Recall   :", recall)
    print("F1 Score :", f1)
    print("AUC      :", auc_score)
    print("Train Time:", train_time)
    print("Test Time :", test_time)

# ==========================================
# Results Table
# ==========================================

df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "AUC",
        "Training Time (s)",
        "Testing Time (s)",
        "Time per Sample (s)"
    ]
)

print("\nFinal Results")
print(df)

# ==========================================
# Save Excel
# ==========================================

excel_path = os.path.join(
    output_base,
    "CoMoFoD_New_Classifiers.xlsx"
)

df.to_excel(
    excel_path,
    index=False
)

print(f"\n✅ Results saved to:\n{excel_path}")

print("\nAvailable trained models:")
print(list(trained_models.keys()))

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

import matplotlib.pyplot as plt
import numpy as np
import os

# ==========================================
# Output Folder
# ==========================================

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

os.makedirs(output_base, exist_ok=True)

# ==========================================
# Process Each Trained Model
# ==========================================

for model_name, model in trained_models.items():

    print("\n" + "="*60)
    print(f"Processing {model_name}")
    print("="*60)

    # ======================================
    # Prediction
    # ======================================

    pred = model.predict(X_test)
    proba = model.predict_proba(X_test)[:, 1]

    # ======================================
    # Classification Report
    # ======================================

    report = classification_report(y_test, pred)

    report_path = os.path.join(
        output_base,
        f"{model_name}_Classification_Report.txt"
    )

    with open(report_path, "w") as f:
        f.write(report)

    # ======================================
    # Confusion Matrix
    # ======================================

    cm = confusion_matrix(y_test, pred)

    plt.figure(figsize=(6,5))

    plt.imshow(cm, cmap="Blues")

    plt.title(f"{model_name} Confusion Matrix")

    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(
                j,
                i,
                str(cm[i, j]),
                ha="center",
                va="center",
                fontsize=12
            )

    plt.colorbar()
    plt.tight_layout()

    cm_path = os.path.join(
        output_base,
        f"{model_name}_Confusion_Matrix.png"
    )

    plt.savefig(
        cm_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    # ======================================
    # ROC Curve
    # ======================================

    fpr, tpr, _ = roc_curve(y_test, proba)

    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(6,5))

    plt.plot(
        fpr,
        tpr,
        linewidth=2,
        label=f"AUC = {roc_auc:.4f}"
    )

    plt.plot(
        [0,1],
        [0,1],
        linestyle="--"
    )

    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")

    plt.title(f"{model_name} ROC Curve")

    plt.legend(loc="lower right")

    plt.grid(True)

    plt.tight_layout()

    roc_path = os.path.join(
        output_base,
        f"{model_name}_ROC_Curve.png"
    )

    plt.savefig(
        roc_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    print(f"✅ Classification Report Saved")
    print(f"✅ Confusion Matrix Saved")
    print(f"✅ ROC Curve Saved")

print("\n" + "="*60)
print("✅ All Results Saved Successfully")
print(f"📂 Folder: {output_base}")
print("="*60)

# ==========================================
# SHAP for All Models
# ==========================================

import os
import shap
import numpy as np
import matplotlib.pyplot as plt

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

os.makedirs(output_base, exist_ok=True)

for model_name, model in trained_models.items():

    print("\n" + "="*60)
    print(f"Generating SHAP for {model_name}")
    print("="*60)

    # ======================================
    # SHAP Explainer
    # ======================================

    explainer = shap.TreeExplainer(model)

    shap_values = explainer.shap_values(X_test)

    # Compatibility with different SHAP versions
    if isinstance(shap_values, list):
        shap_plot_values = shap_values[1]
    else:
        shap_plot_values = shap_values

    # ======================================
    # SHAP Summary Plot
    # ======================================

    shap.summary_plot(
        shap_plot_values,
        X_test,
        show=False
    )

    plt.title(
        f"{model_name} SHAP Summary Plot",
        fontsize=14
    )

    plt.tight_layout()

    summary_path = os.path.join(
        output_base,
        f"{model_name}_SHAP_Summary.png"
    )

    plt.savefig(
        summary_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    # ======================================
    # SHAP Bar Plot
    # ======================================

    shap.summary_plot(
        shap_plot_values,
        X_test,
        plot_type="bar",
        show=False
    )

    plt.title(
        f"{model_name} SHAP Feature Importance",
        fontsize=14
    )

    plt.tight_layout()

    bar_path = os.path.join(
        output_base,
        f"{model_name}_SHAP_Bar.png"
    )

    plt.savefig(
        bar_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close()

    # ======================================
    # Save SHAP Values
    # ======================================

    np.save(
        os.path.join(
            output_base,
            f"{model_name}_SHAP_Values.npy"
        ),
        shap_plot_values
    )

    print(f"✅ Summary Plot Saved")
    print(f"✅ Bar Plot Saved")
    print(f"✅ SHAP Values Saved")

print("\n" + "="*60)
print("✅ All SHAP Results Saved Successfully")
print("="*60)

# ==========================================
# Stacking Ensemble
# LightGBM + XGBoost + CatBoost
# ==========================================

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import time
import joblib
import pandas as pd
import os

# ==========================================
# Output Folder
# ==========================================

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

os.makedirs(output_base, exist_ok=True)

# ==========================================
# Stacking Model
# ==========================================

stack_model = StackingClassifier(

    estimators=[

        (
            'lgbm',
            LGBMClassifier(
                n_estimators=300,
                learning_rate=0.05,
                random_state=42
            )
        ),

        (
            'xgb',
            XGBClassifier(
                eval_metric='logloss',
                random_state=42
            )
        ),

        (
            'cat',
            CatBoostClassifier(
                verbose=0,
                random_state=42
            )
        )
    ],

    final_estimator=LogisticRegression(),
    n_jobs=-1
)

# ==========================================
# Training
# ==========================================

start_train = time.time()

stack_model.fit(X_train, y_train)

train_time = time.time() - start_train

# ==========================================
# Testing
# ==========================================

start_test = time.time()

pred = stack_model.predict(X_test)
proba = stack_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# ==========================================
# Metrics
# ==========================================

acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc_score = roc_auc_score(y_test, proba)

time_per_sample = test_time / len(X_test)

print("\n🔹 Stacking Ensemble")
print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc_score)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", time_per_sample)

# ==========================================
# Save Model
# ==========================================

joblib.dump(
    stack_model,
    os.path.join(
        output_base,
        "CoMoFoD_Stacking_Model.pkl"
    )
)

# ==========================================
# Save TXT Results
# ==========================================

with open(
    os.path.join(
        output_base,
        "Stacking_Results.txt"
    ),
    "w"
) as f:

    f.write(f"Accuracy: {acc*100:.4f}\n")
    f.write(f"Precision: {precision*100:.4f}\n")
    f.write(f"Recall: {recall*100:.4f}\n")
    f.write(f"F1-Score: {f1*100:.4f}\n")
    f.write(f"AUC: {auc_score*100:.4f}\n")
    f.write(f"Training Time (s): {train_time}\n")
    f.write(f"Testing Time (s): {test_time}\n")
    f.write(f"Time per Sample (s): {time_per_sample}\n")

# ==========================================
# Save Excel
# ==========================================

stack_df = pd.DataFrame([{
    "Model": "Stacking Ensemble",
    "Accuracy": acc * 100,
    "Precision": precision * 100,
    "Recall": recall * 100,
    "F1-Score": f1 * 100,
    "AUC": auc_score * 100,
    "Training Time (s)": train_time,
    "Testing Time (s)": test_time,
    "Time per Sample (s)": time_per_sample
}])

stack_df.to_excel(
    os.path.join(
        output_base,
        "CoMoFoD_Stacking_Results.xlsx"
    ),
    index=False
)

print("✅ Stacking model saved")
print("✅ Stacking results saved")

# ==========================================
# Soft Voting Ensemble
# LightGBM + XGBoost + CatBoost
# ==========================================

from sklearn.ensemble import VotingClassifier

from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import pandas as pd
import joblib
import time
import os

# ==========================================
# Output Folder
# ==========================================

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

os.makedirs(output_base, exist_ok=True)

# ==========================================
# Soft Voting Model
# ==========================================

voting_model = VotingClassifier(

    estimators=[

        (
            'lgbm',
            LGBMClassifier(
                n_estimators=300,
                learning_rate=0.05,
                random_state=42
            )
        ),

        (
            'xgb',
            XGBClassifier(
                eval_metric='logloss',
                random_state=42
            )
        ),

        (
            'cat',
            CatBoostClassifier(
                verbose=0,
                random_state=42
            )
        )
    ],

    voting='soft'
)

# ==========================================
# Training
# ==========================================

start_train = time.time()

voting_model.fit(X_train, y_train)

train_time = time.time() - start_train

# ==========================================
# Testing
# ==========================================

start_test = time.time()

pred = voting_model.predict(X_test)
proba = voting_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# ==========================================
# Metrics
# ==========================================

acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc_score = roc_auc_score(y_test, proba)

time_per_sample = test_time / len(X_test)

print("\n🔹 Soft Voting Ensemble")

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc_score)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", time_per_sample)

# ==========================================
# Save Model
# ==========================================

joblib.dump(
    voting_model,
    os.path.join(
        output_base,
        "CoMoFoD_SoftVoting_Model.pkl"
    )
)

# ==========================================
# Save TXT Results
# ==========================================

with open(
    os.path.join(
        output_base,
        "SoftVoting_Results.txt"
    ),
    "w"
) as f:

    f.write(f"Accuracy: {acc*100:.4f}\n")
    f.write(f"Precision: {precision*100:.4f}\n")
    f.write(f"Recall: {recall*100:.4f}\n")
    f.write(f"F1-Score: {f1*100:.4f}\n")
    f.write(f"AUC: {auc_score*100:.4f}\n")
    f.write(f"Training Time (s): {train_time}\n")
    f.write(f"Testing Time (s): {test_time}\n")
    f.write(f"Time per Sample (s): {time_per_sample}\n")

# ==========================================
# Save Excel
# ==========================================

voting_df = pd.DataFrame([{
    "Model": "Soft Voting Ensemble",
    "Accuracy": acc * 100,
    "Precision": precision * 100,
    "Recall": recall * 100,
    "F1-Score": f1 * 100,
    "AUC": auc_score * 100,
    "Training Time (s)": train_time,
    "Testing Time (s)": test_time,
    "Time per Sample (s)": time_per_sample
}])

voting_df.to_excel(
    os.path.join(
        output_base,
        "CoMoFoD_SoftVoting_Results.xlsx"
    ),
    index=False
)

print("✅ Soft Voting model saved")
print("✅ Soft Voting results saved")

import pandas as pd
import os

output_base = "/content/drive/MyDrive/Experiments/CoMoFoD_Final"

# نتائج المصنفات الفردية
cls_df = pd.read_excel(
    os.path.join(output_base, "CoMoFoD_New_Classifiers.xlsx"),
    engine="openpyxl"
)

# نتائج Soft Voting
soft_df = pd.read_excel(
    os.path.join(output_base, "CoMoFoD_SoftVoting_Results.xlsx"),
    engine="openpyxl"
)

# نتائج Stacking
stack_df = pd.read_excel(
    os.path.join(output_base, "CoMoFoD_Stacking_Results.xlsx"),
    engine="openpyxl"
)

# دمج الجميع
final_df = pd.concat(
    [cls_df, soft_df, stack_df],
    ignore_index=True
)

# ترتيب حسب Accuracy
final_df = final_df.sort_values(
    by="Accuracy",
    ascending=False
)

# إعادة الترقيم
final_df.reset_index(drop=True, inplace=True)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

print(final_df)

# حفظ الجدول النهائي
final_df.to_excel(
    os.path.join(
        output_base,
        "CoMoFoD_Final_Results.xlsx"
    ),
    index=False
)

print("✅ CoMoFoD Final comparison table saved")