# -*- coding: utf-8 -*-
"""IMD2020feature extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xc1alQcE1apaQyzKkCRPX4Qe_hA-i-7W
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import tensorflow as tf
import numpy as np

# ===============================
# إعدادات عامة
# ===============================
IMG_SIZE_MAP = 128
IMG_SIZE_RGB = 224
BATCH_SIZE = 64
AUTOTUNE = tf.data.AUTOTUNE

# ===============================
# مسار التجربة
# ===============================
output_base = "/content/drive/MyDrive/Experiments/IMD2020_Classification_new"

os.makedirs(output_base, exist_ok=True)

print("Using experiment folder:", output_base)

# ===============================
# البحث عن الصورة الأصلية
# ===============================
def find_rgb_image(rgb_folder, name):
    exts = ['.jpg','.png','.jpeg','.tif','.tiff','.bmp']
    for ext in exts:
        p = os.path.join(rgb_folder, name + ext)
        if os.path.exists(p):
            return p
    return None


# ===============================
# ربط maps مع RGB
# ===============================
def get_all_pairs(map_folder, rgb_folder, label):

    data = []
    missing = 0

    for f in os.listdir(map_folder):
        if not f.lower().endswith('.tiff'):
            continue

        name = os.path.splitext(f)[0]

        map_path = os.path.join(map_folder, f)
        rgb_path = find_rgb_image(rgb_folder, name)

        if rgb_path is not None:
            data.append((map_path, rgb_path, label))
        else:
            missing += 1

    print(f"Label {label} → Total pairs: {len(data)}, Missing: {missing}")

    return data

import cv2
import numpy as np
import tensorflow as tf

# ==========================================
# قراءة صور MAP (TIFF)
# ==========================================
def load_map_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
        print("⚠️ Missing MAP:", path)
        img = np.zeros((IMG_SIZE_MAP, IMG_SIZE_MAP), dtype=np.uint8)

    if len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

    img = cv2.resize(img, (IMG_SIZE_MAP, IMG_SIZE_MAP))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# قراءة صور RGB
# ==========================================
def load_rgb_cv2(path):

    path = path.numpy().decode()

    img = cv2.imread(path)

    if img is None:
        print("⚠️ Missing RGB:", path)
        img = np.zeros((IMG_SIZE_RGB, IMG_SIZE_RGB, 3), dtype=np.uint8)

    img = cv2.resize(img, (IMG_SIZE_RGB, IMG_SIZE_RGB))
    img = img.astype(np.float32) / 255.0

    return img


# ==========================================
# parse_function
# ==========================================
def parse_function(map_path, rgb_path, label):

    map_img = tf.py_function(load_map_cv2, [map_path], tf.float32)
    map_img.set_shape((IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    rgb_img = tf.py_function(load_rgb_cv2, [rgb_path], tf.float32)
    rgb_img.set_shape((IMG_SIZE_RGB, IMG_SIZE_RGB, 3))

    return (map_img, rgb_img), label

# ==========================================
# build_dataset
# ==========================================
def build_dataset(data):

    print("Total samples:", len(data))

    map_paths = [d[0] for d in data]
    rgb_paths = [d[1] for d in data]
    labels    = [d[2] for d in data]

    dataset = tf.data.Dataset.from_tensor_slices((map_paths, rgb_paths, labels))

    dataset = dataset.map(
        lambda m, r, y: parse_function(m, r, y),
        num_parallel_calls=tf.data.AUTOTUNE
    )

    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

# CNN للـ maps
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model

def build_map_cnn():

    inp = Input(shape=(IMG_SIZE_MAP, IMG_SIZE_MAP, 3))

    x = Conv2D(32,3,activation='relu',padding='same')(inp)
    x = MaxPooling2D()(x)

    x = Conv2D(64,3,activation='relu',padding='same')(x)
    x = MaxPooling2D()(x)

    x = Conv2D(128,3,activation='relu',padding='same')(x)

    x = GlobalAveragePooling2D()(x)

    model = Model(inp, x)

    print("Map CNN output shape:", model.output_shape)

    return model

#ResNet50 للصور الملونة
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input

resnet = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(IMG_SIZE_RGB, IMG_SIZE_RGB, 3)
)

resnet.trainable = False

print("ResNet loaded. Output shape:", resnet.output_shape)

# Block 7 — استخراج الميزات
map_model = build_map_cnn()

def extract_features(dataset):

    all_features = []
    all_labels = []

    for i, ((maps, rgbs), labels) in enumerate(dataset):

        # CNN features (maps)
        f1 = map_model(maps, training=False)

        # ResNet features (rgb)
        rgbs_resnet = preprocess_input(rgbs * 255.0)
        f2 = resnet(rgbs_resnet, training=False)
        f2 = tf.keras.layers.GlobalAveragePooling2D()(f2)

        # Normalization
        f1 = (f1 - tf.reduce_mean(f1)) / (tf.math.reduce_std(f1) + 1e-8)
        f2 = (f2 - tf.reduce_mean(f2)) / (tf.math.reduce_std(f2) + 1e-8)

        # Fusion
        fused = tf.concat([f1, f2], axis=1)

        all_features.append(fused.numpy())
        all_labels.append(labels.numpy())

        if i % 10 == 0:
            print(f"Processed batch {i}")

    features = np.vstack(all_features)
    labels   = np.concatenate(all_labels)

    print("Final feature shape:", features.shape)

    return features, labels

# ===============================
# تشغيل النظام (مرتبط بالتجربة)
# ===============================

MAP_AU = "/content/drive/MyDrive/Experiments/IMD2020_TEST_AE_20260403_2051/maps/Au"
MAP_TP = "/content/drive/MyDrive/Experiments/IMD2020_TEST_AE_20260403_2051/maps/Tp"

RGB_AU = "/content/drive/MyDrive/IMD2020_TEST/REAL"
RGB_TP = "/content/drive/MyDrive/IMD2020_TEST/FAKE"

data_au = get_all_pairs(MAP_AU, RGB_AU, 0)
data_tp = get_all_pairs(MAP_TP, RGB_TP, 1)

all_data = data_au + data_tp

print("Total samples:", len(all_data))

dataset = build_dataset(all_data)

features, labels = extract_features(dataset)

print("Feature shape:", features.shape)

# ✅ حفظ الميزات داخل مجلد التجربة

features_path = os.path.join(output_base, "features.npy")
labels_path   = os.path.join(output_base, "labels.npy")

np.save(features_path, features)
np.save(labels_path, labels)

print("✅ Features saved at:", features_path)
features_path = os.path.join(output_base, "features.npy")
labels_path   = os.path.join(output_base, "labels.npy")

np.save(features_path, features)
np.save(labels_path, labels)

print("✅ Features saved at:", features_path)
print("Features shape:", features.shape)
print("Labels shape:", labels.shape)

import numpy as np

features = np.load(
    "/content/drive/MyDrive/Experiments/IMD2020_Classification_new/features.npy"
)

labels = np.load(
    "/content/drive/MyDrive/Experiments/IMD2020_Classification_new/labels.npy"
)

print(features.shape)
print(labels.shape)

# التدريب
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lightgbm import LGBMClassifier
import joblib  # 🔥 مهم
import time
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# ===============================
# تحميل
# ===============================
base_path = "/content/drive/MyDrive/Experiments/IMD2020_Classification_new"
output_base = base_path

features = np.load(base_path + "/features.npy")
labels   = np.load(base_path + "/labels.npy")

# ===============================
# تقسيم
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

# ===============================
# Scaling
# ===============================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ===============================
# تدريب
# ===============================
start_train = time.time()

model = LGBMClassifier(n_estimators=300, learning_rate=0.05)
model.fit(X_train, y_train)

train_time = time.time() - start_train

# ===============================
# تقييم
# ===============================
start_test = time.time()

pred = model.predict(X_test)
proba = model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

print("Accuracy:", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall:", recall_score(y_test, pred))
print("F1-Score:", f1_score(y_test, pred))
print("AUC:", roc_auc_score(y_test, proba))

print("Training Time (s):", train_time)
print("Testing Time (s):", test_time)
print("Time per Sample (s):", test_time / len(X_test))

# ===============================
# 🔥 حفظ النموذج
# ===============================
joblib.dump(model, os.path.join(base_path, "model.pkl"))
joblib.dump(scaler, os.path.join(base_path, "scaler.pkl"))

print("✅ Model & Scaler saved!")

# ===============================
# تقرير النتائج + حفظها
# ===============================
import matplotlib.pyplot as plt
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)

# ==========================================
# 1. Classification Report (حفظ)
# ==========================================
report = classification_report(y_test, pred)

print("\n📊 Classification Report:\n")
print(report)

report_path = os.path.join(output_base, "classification_report.txt")
with open(report_path, "w") as f:
    f.write(report)

# ==========================================
# 2. Confusion Matrix
# ==========================================
cm = confusion_matrix(y_test, pred)

print("\n📌 Confusion Matrix:\n", cm)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

plt.colorbar()

# حفظ الصورة
cm_path = os.path.join(output_base, "confusion_matrix.png")
plt.savefig(cm_path)

plt.show()

# ==========================================
# 3. ROC Curve + AUC
# ==========================================
fpr, tpr, thresholds = roc_curve(y_test, proba)
roc_auc = auc(fpr, tpr)

print("\n📈 AUC:", roc_auc)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

# حفظ الرسم
roc_path = os.path.join(output_base, "roc_curve.png")
plt.savefig(roc_path)

plt.show()

# ==========================================
# 4. حفظ القيم الرقمية
# ==========================================
metrics_path = os.path.join(output_base, "metrics.txt")

with open(metrics_path, "w") as f:
    f.write(f"Accuracy: {accuracy_score(y_test, pred)}\n")
    f.write(f"Precision: {precision_score(y_test, pred)}\n")
    f.write(f"Recall: {recall_score(y_test, pred)}\n")
    f.write(f"F1-Score: {f1_score(y_test, pred)}\n")
    f.write(f"AUC: {roc_auc}\n")
    f.write(f"Training Time (s): {train_time}\n")
    f.write(f"Testing Time (s): {test_time}\n")
    f.write(f"Time per Sample (s): {test_time / len(X_test)}\n")

print("✅ Results saved in:", output_base)

# تفسير الفيجرات
# XAI - SHAP
# ===============================
import shap
import matplotlib.pyplot as plt

# إنشاء المفسر
explainer = shap.TreeExplainer(model)

# حساب SHAP
shap_values = explainer.shap_values(X_test)

# ==========================================
# حفظ الرسم
# ==========================================
plt.figure()

shap.summary_plot(shap_values, X_test, show=False)

shap_path = os.path.join(output_base, "shap_summary.png")
plt.savefig(shap_path, bbox_inches='tight')

plt.show()

print("✅ SHAP saved at:", shap_path)

!pip install catboost -q

# ===============================
# مقارنة خوارزميات متعددة - IMD2020
# ===============================
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import numpy as np
import pandas as pd
import joblib
import time
import os

# ==========================================
# تحميل الميزات من مجلد التجربة
# ==========================================
features_path = os.path.join(output_base, "features.npy")
labels_path   = os.path.join(output_base, "labels.npy")

features = np.load(features_path)
labels   = np.load(labels_path)

# ==========================================
# تقسيم
# ==========================================
X_train, X_test, y_train, y_test = train_test_split(
    features,
    labels,
    test_size=0.2,
    random_state=42
)

# ==========================================
# Scaling
# ==========================================
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ==========================================
# النماذج
# ==========================================
models = {

    "LightGBM": LGBMClassifier(
        n_estimators=300
    ),

    "RandomForest": RandomForestClassifier(
        n_estimators=200
    ),

    "ExtraTrees": ExtraTreesClassifier(
        n_estimators=500,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        eval_metric='logloss'
    ),

    "CatBoost": CatBoostClassifier(
        verbose=0
    ),

    "SVM": SVC(
        probability=True
    )
}

results = []

# ==========================================
# تدريب وتقييم
# ==========================================
for name, m in models.items():

    print(f"\n🔹 Training {name}...")

    start_train = time.time()

    m.fit(X_train, y_train)

    train_time = time.time() - start_train

    start_test = time.time()

    pred = m.predict(X_test)
    proba = m.predict_proba(X_test)[:,1]

    test_time = time.time() - start_test

    acc = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    auc = roc_auc_score(y_test, proba)

    print("Accuracy:", acc)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC:", auc)
    print("Training Time:", train_time)
    print("Testing Time:", test_time)

    results.append([
        name,
        acc,
        precision,
        recall,
        f1,
        auc,
        train_time,
        test_time,
        test_time / len(X_test)
    ])

    # حفظ النموذج
    model_path = os.path.join(
        output_base,
        f"{name}_model.pkl"
    )

    joblib.dump(m, model_path)

# ==========================================
# إنشاء الجدول
# ==========================================
df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "AUC",
        "Training Time (s)",
        "Testing Time (s)",
        "Time per Sample (s)"
    ]
)

df = df.sort_values(
    by="Accuracy",
    ascending=False
)

print("\n")
print(df)

# ==========================================
# حفظ الجدول
# ==========================================
csv_path = os.path.join(
    output_base,
    "model_comparison.csv"
)

xlsx_path = os.path.join(
    output_base,
    "model_comparison.xlsx"
)

df.to_csv(csv_path, index=False)
df.to_excel(xlsx_path, index=False)

print("\n✅ Results saved in:", output_base)

#Ensemble stacking
from sklearn.ensemble import StackingClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import time
import joblib
import os

stack_model = StackingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(
            n_estimators=500,
            random_state=42
        )),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    final_estimator=LogisticRegression(),
    n_jobs=-1
)

# ==========================================
# Training Time
# ==========================================
start_train = time.time()

stack_model.fit(X_train, y_train)

train_time = time.time() - start_train

# ==========================================
# Testing Time
# ==========================================
start_test = time.time()

pred = stack_model.predict(X_test)
proba = stack_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# ==========================================
# Metrics
# ==========================================
acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc = roc_auc_score(y_test, proba)
time_per_sample = test_time / len(X_test)

print("\n🔹 Stacking Ensemble")

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", time_per_sample)

# ==========================================
# Save Model
# ==========================================
model_path = os.path.join(
    output_base,
    "Stacking_model.pkl"
)

joblib.dump(stack_model, model_path)

# ==========================================
# Save Metrics
# ==========================================
results_path = os.path.join(
    output_base,
    "Stacking_results.txt"
)

with open(results_path, "w") as f:
    f.write(f"Accuracy: {acc}\n")
    f.write(f"Precision: {precision}\n")
    f.write(f"Recall: {recall}\n")
    f.write(f"F1-Score: {f1}\n")
    f.write(f"AUC: {auc}\n")
    f.write(f"Training Time (s): {train_time}\n")
    f.write(f"Testing Time (s): {test_time}\n")
    f.write(f"Time per Sample (s): {time_per_sample}\n")

print("✅ Stacking model saved at:", model_path)
print("✅ Stacking results saved at:", results_path)

#Ensemble Voiting
from sklearn.ensemble import VotingClassifier, ExtraTreesClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import time
import joblib
import os

voting_model = VotingClassifier(
    estimators=[
        ('lgbm', LGBMClassifier(n_estimators=200)),
        ('rf', RandomForestClassifier(n_estimators=200)),
        ('xgb', XGBClassifier(eval_metric='logloss')),
        ('extra', ExtraTreesClassifier(
            n_estimators=500,
            random_state=42
        )),
        ('cat', CatBoostClassifier(verbose=0))
    ],
    voting='soft'
)

# ==========================================
# Training Time
# ==========================================
start_train = time.time()

voting_model.fit(X_train, y_train)

train_time = time.time() - start_train

# ==========================================
# Testing Time
# ==========================================
start_test = time.time()

pred = voting_model.predict(X_test)
proba = voting_model.predict_proba(X_test)[:,1]

test_time = time.time() - start_test

# ==========================================
# Metrics
# ==========================================
acc = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)
auc = roc_auc_score(y_test, proba)

time_per_sample = test_time / len(X_test)

print("\n🔹 Soft Voting Ensemble")

print("Accuracy:", acc)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("AUC:", auc)

print("Training Time:", train_time)
print("Testing Time:", test_time)
print("Time per Sample:", time_per_sample)

# ==========================================
# Save Model
# ==========================================
model_path = os.path.join(
    output_base,
    "SoftVoting_model.pkl"
)

joblib.dump(voting_model, model_path)

# ==========================================
# Save Metrics
# ==========================================
results_path = os.path.join(
    output_base,
    "SoftVoting_results.txt"
)

with open(results_path, "w") as f:
    f.write(f"Accuracy: {acc}\n")
    f.write(f"Precision: {precision}\n")
    f.write(f"Recall: {recall}\n")
    f.write(f"F1-Score: {f1}\n")
    f.write(f"AUC: {auc}\n")
    f.write(f"Training Time (s): {train_time}\n")
    f.write(f"Testing Time (s): {test_time}\n")
    f.write(f"Time per Sample (s): {time_per_sample}\n")

print("✅ Soft Voting model saved at:", model_path)
print("✅ Soft Voting results saved at:", results_path)

import pandas as pd
import os

results = [

    ["LightGBM",     0.9950, 0.994939, 0.994939, 0.994939, 0.998681,  25.017058, 0.034717, 0.000017],

    ["Stacking",     0.9945, 0.993933, 0.994939, 0.994436, 0.999428, 863.425307, 1.013681, 0.000507],

    ["Soft Voting",  0.9875, 0.981982, 0.992915, 0.987418, 0.998349, 330.583324, 1.018446, 0.000509],

    ["CatBoost",     0.9735, 0.966102, 0.980769, 0.973380, 0.994025, 100.802198, 0.057143, 0.000029],

    ["XGBoost",      0.9380, 0.939919, 0.934211, 0.937056, 0.983942,  19.984613, 0.007917, 0.000004],

    ["RandomForest", 0.7055, 0.677966, 0.769231, 0.720721, 0.799501, 146.658460, 0.209667, 0.000105],

    ["ExtraTrees",   0.5535, 0.545195, 0.579960, 0.562040, 0.561426,  51.220283, 0.680291, 0.000340],

    ["SVM",          0.4885, 0.483189, 0.509109, 0.495811, 0.530175, 505.572083, 69.819105, 0.034910]

]

df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1-Score",
        "AUC",
        "Training Time (s)",
        "Testing Time (s)",
        "Time per Sample (s)"
    ]
)

# ترتيب حسب Accuracy
df = df.sort_values(
    by="Accuracy",
    ascending=False
)

print("\n📊 Final IMD2020 Results\n")
print(df)

# حفظ النتائج
csv_path = os.path.join(
    output_base,
    "Final_IMD2020_Results.csv"
)

xlsx_path = os.path.join(
    output_base,
    "Final_IMD2020_Results.xlsx"
)

df.to_csv(csv_path, index=False)
df.to_excel(xlsx_path, index=False)

print("\n✅ CSV saved at:", csv_path)
print("✅ Excel saved at:", xlsx_path)